### ISSUE TITLE
Full-screen support is missing

### ISSUE THREAD

**Issue by alensuljkanovic** [nenad-misic/zMile#1]
First of all, I have to say that zMile is a really fun game. However, the lack of full-screen support is drastically aggravating the user experience.

**Comment by nenad-misic** [comment]
Hello alensuljkanovic,


I'm glad to hear you're ejoying this little piece of art.

Full-screen support has been marked as a top-priority task on our scrum board. There is nothing more important to us than satisfaction of each and every customer.

This will be done ASAP.
